package platform

import "strings"

// InferTimezone maps a free-text location string to an IANA timezone ID.
// Matching is case-insensitive substring search; the first match wins.
// Returns "UTC" for unknown or empty locations.
func InferTimezone(location string) string {
	if location == "" {
		return "UTC"
	}
	low := strings.ToLower(location)
	for _, entry := range timezoneTable {
		if strings.Contains(low, entry.keyword) {
			return entry.tz
		}
	}
	return "UTC"
}

type tzEntry struct {
	keyword string
	tz      string
}

// timezoneTable maps lowercase location keywords to IANA timezone IDs.
// Order matters — more specific entries should come before broad ones.
var timezoneTable = []tzEntry{
	// ── East Asia ────────────────────────────────────────────────────────────
	{"taipei", "Asia/Taipei"},
	{"taiwan", "Asia/Taipei"},
	{"hong kong", "Asia/Hong_Kong"},
	{"hongkong", "Asia/Hong_Kong"},
	{"macau", "Asia/Macau"},
	{"macao", "Asia/Macau"},
	{"shanghai", "Asia/Shanghai"},
	{"beijing", "Asia/Shanghai"},
	{"shenzhen", "Asia/Shanghai"},
	{"guangzhou", "Asia/Shanghai"},
	{"chengdu", "Asia/Shanghai"},
	{"hangzhou", "Asia/Shanghai"},
	{"wuhan", "Asia/Shanghai"},
	{"nanjing", "Asia/Shanghai"},
	{"chongqing", "Asia/Chongqing"},
	{"urumqi", "Asia/Urumqi"},
	{"china", "Asia/Shanghai"},
	{"mainland", "Asia/Shanghai"},
	{"tokyo", "Asia/Tokyo"},
	{"osaka", "Asia/Tokyo"},
	{"kyoto", "Asia/Tokyo"},
	{"japan", "Asia/Tokyo"},
	{"seoul", "Asia/Seoul"},
	{"busan", "Asia/Seoul"},
	{"korea", "Asia/Seoul"},
	{"pyongyang", "Asia/Pyongyang"},

	// ── Southeast Asia ────────────────────────────────────────────────────────
	{"singapore", "Asia/Singapore"},
	{"kuala lumpur", "Asia/Kuala_Lumpur"},
	{"malaysia", "Asia/Kuala_Lumpur"},
	{"jakarta", "Asia/Jakarta"},
	{"indonesia", "Asia/Jakarta"},
	{"bali", "Asia/Makassar"},
	{"bangkok", "Asia/Bangkok"},
	{"thailand", "Asia/Bangkok"},
	{"hanoi", "Asia/Ho_Chi_Minh"},
	{"ho chi minh", "Asia/Ho_Chi_Minh"},
	{"vietnam", "Asia/Ho_Chi_Minh"},
	{"manila", "Asia/Manila"},
	{"philippines", "Asia/Manila"},
	{"yangon", "Asia/Rangoon"},
	{"myanmar", "Asia/Rangoon"},
	{"phnom penh", "Asia/Phnom_Penh"},
	{"cambodia", "Asia/Phnom_Penh"},
	{"vientiane", "Asia/Vientiane"},
	{"laos", "Asia/Vientiane"},
	{"brunei", "Asia/Brunei"},

	// ── South Asia ────────────────────────────────────────────────────────────
	{"mumbai", "Asia/Kolkata"},
	{"delhi", "Asia/Kolkata"},
	{"bangalore", "Asia/Kolkata"},
	{"kolkata", "Asia/Kolkata"},
	{"chennai", "Asia/Kolkata"},
	{"hyderabad", "Asia/Kolkata"},
	{"india", "Asia/Kolkata"},
	{"karachi", "Asia/Karachi"},
	{"islamabad", "Asia/Karachi"},
	{"lahore", "Asia/Karachi"},
	{"pakistan", "Asia/Karachi"},
	{"dhaka", "Asia/Dhaka"},
	{"bangladesh", "Asia/Dhaka"},
	{"colombo", "Asia/Colombo"},
	{"sri lanka", "Asia/Colombo"},
	{"kathmandu", "Asia/Kathmandu"},
	{"nepal", "Asia/Kathmandu"},
	{"kabul", "Asia/Kabul"},
	{"afghanistan", "Asia/Kabul"},

	// ── Central Asia & Middle East ────────────────────────────────────────────
	{"dubai", "Asia/Dubai"},
	{"abu dhabi", "Asia/Dubai"},
	{"uae", "Asia/Dubai"},
	{"riyadh", "Asia/Riyadh"},
	{"jeddah", "Asia/Riyadh"},
	{"saudi", "Asia/Riyadh"},
	{"doha", "Asia/Qatar"},
	{"qatar", "Asia/Qatar"},
	{"kuwait", "Asia/Kuwait"},
	{"muscat", "Asia/Muscat"},
	{"oman", "Asia/Muscat"},
	{"bahrain", "Asia/Bahrain"},
	{"baghdad", "Asia/Baghdad"},
	{"iraq", "Asia/Baghdad"},
	{"tehran", "Asia/Tehran"},
	{"iran", "Asia/Tehran"},
	{"istanbul", "Europe/Istanbul"},
	{"ankara", "Europe/Istanbul"},
	{"turkey", "Europe/Istanbul"},
	{"beirut", "Asia/Beirut"},
	{"lebanon", "Asia/Beirut"},
	{"amman", "Asia/Amman"},
	{"jordan", "Asia/Amman"},
	{"jerusalem", "Asia/Jerusalem"},
	{"tel aviv", "Asia/Jerusalem"},
	{"israel", "Asia/Jerusalem"},
	{"damascus", "Asia/Damascus"},
	{"syria", "Asia/Damascus"},
	{"nicosia", "Asia/Nicosia"},
	{"cyprus", "Asia/Nicosia"},
	{"tashkent", "Asia/Tashkent"},
	{"uzbekistan", "Asia/Tashkent"},
	{"almaty", "Asia/Almaty"},
	{"kazakhstan", "Asia/Almaty"},
	{"yerevan", "Asia/Yerevan"},
	{"armenia", "Asia/Yerevan"},
	{"baku", "Asia/Baku"},
	{"azerbaijan", "Asia/Baku"},
	{"tbilisi", "Asia/Tbilisi"},
	{"georgia", "Asia/Tbilisi"},

	// ── Europe ────────────────────────────────────────────────────────────────
	{"london", "Europe/London"},
	{"manchester", "Europe/London"},
	{"birmingham", "Europe/London"},
	{"edinburgh", "Europe/London"},
	{"uk", "Europe/London"},
	{"england", "Europe/London"},
	{"scotland", "Europe/London"},
	{"wales", "Europe/London"},
	{"ireland", "Europe/Dublin"},
	{"dublin", "Europe/Dublin"},
	{"lisbon", "Europe/Lisbon"},
	{"portugal", "Europe/Lisbon"},
	{"madrid", "Europe/Madrid"},
	{"barcelona", "Europe/Madrid"},
	{"spain", "Europe/Madrid"},
	{"paris", "Europe/Paris"},
	{"lyon", "Europe/Paris"},
	{"france", "Europe/Paris"},
	{"amsterdam", "Europe/Amsterdam"},
	{"netherlands", "Europe/Amsterdam"},
	{"berlin", "Europe/Berlin"},
	{"munich", "Europe/Berlin"},
	{"hamburg", "Europe/Berlin"},
	{"frankfurt", "Europe/Berlin"},
	{"germany", "Europe/Berlin"},
	{"vienna", "Europe/Vienna"},
	{"austria", "Europe/Vienna"},
	{"zurich", "Europe/Zurich"},
	{"geneva", "Europe/Zurich"},
	{"switzerland", "Europe/Zurich"},
	{"rome", "Europe/Rome"},
	{"milan", "Europe/Rome"},
	{"italy", "Europe/Rome"},
	{"brussels", "Europe/Brussels"},
	{"belgium", "Europe/Brussels"},
	{"luxembourg", "Europe/Luxembourg"},
	{"stockholm", "Europe/Stockholm"},
	{"sweden", "Europe/Stockholm"},
	{"oslo", "Europe/Oslo"},
	{"norway", "Europe/Oslo"},
	{"copenhagen", "Europe/Copenhagen"},
	{"denmark", "Europe/Copenhagen"},
	{"helsinki", "Europe/Helsinki"},
	{"finland", "Europe/Helsinki"},
	{"warsaw", "Europe/Warsaw"},
	{"poland", "Europe/Warsaw"},
	{"prague", "Europe/Prague"},
	{"czech", "Europe/Prague"},
	{"bratislava", "Europe/Bratislava"},
	{"slovakia", "Europe/Bratislava"},
	{"budapest", "Europe/Budapest"},
	{"hungary", "Europe/Budapest"},
	{"bucharest", "Europe/Bucharest"},
	{"romania", "Europe/Bucharest"},
	{"sofia", "Europe/Sofia"},
	{"bulgaria", "Europe/Sofia"},
	{"athens", "Europe/Athens"},
	{"greece", "Europe/Athens"},
	{"zagreb", "Europe/Zagreb"},
	{"croatia", "Europe/Zagreb"},
	{"belgrade", "Europe/Belgrade"},
	{"serbia", "Europe/Belgrade"},
	{"kyiv", "Europe/Kiev"},
	{"kiev", "Europe/Kiev"},
	{"ukraine", "Europe/Kiev"},
	{"moscow", "Europe/Moscow"},
	{"saint petersburg", "Europe/Moscow"},
	{"st. petersburg", "Europe/Moscow"},
	{"russia", "Europe/Moscow"},
	{"riga", "Europe/Riga"},
	{"latvia", "Europe/Riga"},
	{"tallinn", "Europe/Tallinn"},
	{"estonia", "Europe/Tallinn"},
	{"vilnius", "Europe/Vilnius"},
	{"lithuania", "Europe/Vilnius"},
	{"reykjavik", "Atlantic/Reykjavik"},
	{"iceland", "Atlantic/Reykjavik"},

	// ── Africa ────────────────────────────────────────────────────────────────
	{"cairo", "Africa/Cairo"},
	{"egypt", "Africa/Cairo"},
	{"casablanca", "Africa/Casablanca"},
	{"morocco", "Africa/Casablanca"},
	{"lagos", "Africa/Lagos"},
	{"abuja", "Africa/Lagos"},
	{"nigeria", "Africa/Lagos"},
	{"nairobi", "Africa/Nairobi"},
	{"kenya", "Africa/Nairobi"},
	{"johannesburg", "Africa/Johannesburg"},
	{"cape town", "Africa/Johannesburg"},
	{"south africa", "Africa/Johannesburg"},
	{"addis ababa", "Africa/Addis_Ababa"},
	{"ethiopia", "Africa/Addis_Ababa"},
	{"accra", "Africa/Accra"},
	{"ghana", "Africa/Accra"},
	{"dakar", "Africa/Dakar"},
	{"senegal", "Africa/Dakar"},
	{"tunis", "Africa/Tunis"},
	{"tunisia", "Africa/Tunis"},
	{"algiers", "Africa/Algiers"},
	{"algeria", "Africa/Algiers"},
	{"tripoli", "Africa/Tripoli"},
	{"libya", "Africa/Tripoli"},
	{"khartoum", "Africa/Khartoum"},
	{"sudan", "Africa/Khartoum"},
	{"kinshasa", "Africa/Kinshasa"},
	{"congo", "Africa/Kinshasa"},
	{"dar es salaam", "Africa/Dar_es_Salaam"},
	{"tanzania", "Africa/Dar_es_Salaam"},
	{"kampala", "Africa/Kampala"},
	{"uganda", "Africa/Kampala"},

	// ── North America ─────────────────────────────────────────────────────────
	{"new york", "America/New_York"},
	{"boston", "America/New_York"},
	{"philadelphia", "America/New_York"},
	{"washington", "America/New_York"},
	{"miami", "America/New_York"},
	{"atlanta", "America/New_York"},
	{"detroit", "America/Detroit"},
	{"chicago", "America/Chicago"},
	{"dallas", "America/Chicago"},
	{"houston", "America/Chicago"},
	{"minneapolis", "America/Chicago"},
	{"kansas city", "America/Chicago"},
	{"denver", "America/Denver"},
	{"salt lake city", "America/Denver"},
	{"phoenix", "America/Phoenix"},
	{"los angeles", "America/Los_Angeles"},
	{"san francisco", "America/Los_Angeles"},
	{"seattle", "America/Los_Angeles"},
	{"portland", "America/Los_Angeles"},
	{"las vegas", "America/Los_Angeles"},
	{"san diego", "America/Los_Angeles"},
	{"silicon valley", "America/Los_Angeles"},
	{"bay area", "America/Los_Angeles"},
	{"california", "America/Los_Angeles"},
	{"toronto", "America/Toronto"},
	{"ottawa", "America/Toronto"},
	{"montreal", "America/Montreal"},
	{"vancouver", "America/Vancouver"},
	{"calgary", "America/Edmonton"},
	{"edmonton", "America/Edmonton"},
	{"winnipeg", "America/Winnipeg"},
	{"canada", "America/Toronto"},
	{"mexico city", "America/Mexico_City"},
	{"guadalajara", "America/Mexico_City"},
	{"mexico", "America/Mexico_City"},
	{"havana", "America/Havana"},
	{"cuba", "America/Havana"},

	// ── Central & South America ───────────────────────────────────────────────
	{"bogota", "America/Bogota"},
	{"colombia", "America/Bogota"},
	{"lima", "America/Lima"},
	{"peru", "America/Lima"},
	{"quito", "America/Guayaquil"},
	{"ecuador", "America/Guayaquil"},
	{"caracas", "America/Caracas"},
	{"venezuela", "America/Caracas"},
	{"la paz", "America/La_Paz"},
	{"bolivia", "America/La_Paz"},
	{"santiago", "America/Santiago"},
	{"chile", "America/Santiago"},
	{"buenos aires", "America/Argentina/Buenos_Aires"},
	{"argentina", "America/Argentina/Buenos_Aires"},
	{"montevideo", "America/Montevideo"},
	{"uruguay", "America/Montevideo"},
	{"asuncion", "America/Asuncion"},
	{"paraguay", "America/Asuncion"},
	{"sao paulo", "America/Sao_Paulo"},
	{"rio de janeiro", "America/Sao_Paulo"},
	{"brasilia", "America/Sao_Paulo"},
	{"brazil", "America/Sao_Paulo"},

	// ── Oceania ───────────────────────────────────────────────────────────────
	{"sydney", "Australia/Sydney"},
	{"melbourne", "Australia/Melbourne"},
	{"brisbane", "Australia/Brisbane"},
	{"perth", "Australia/Perth"},
	{"adelaide", "Australia/Adelaide"},
	{"canberra", "Australia/Sydney"},
	{"australia", "Australia/Sydney"},
	{"auckland", "Pacific/Auckland"},
	{"wellington", "Pacific/Auckland"},
	{"new zealand", "Pacific/Auckland"},
	{"honolulu", "Pacific/Honolulu"},
	{"hawaii", "Pacific/Honolulu"},
	{"fiji", "Pacific/Fiji"},

	// ── USA fallback (broad) ──────────────────────────────────────────────────
	{"usa", "America/New_York"},
	{"united states", "America/New_York"},
	{"america", "America/New_York"},

	// ── Internet / joke locations ──────────────────────────────────────────────
	// These match common social-media bio locations that don't map to a real place.
	// They fall through to UTC naturally, but listing them explicitly documents intent.
}
