# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fishnet < Formula
  desc "Simulation and analysis toolkit with ONNX-powered NLP"
  homepage "https://github.com/kidneyweakx/fishnet"
  version "0.1.0"
  license "AGPL-3.0"

  depends_on "onnxruntime"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kidneyweakx/fishnet/releases/download/v0.1.0/fishnet_0.1.0_darwin_x86_64.tar.gz"
      sha256 "a34334bf3cf8780d232035c803a39f63750b59b38fa8285130afd3043d290f29"

      def install
        bin.install "fishnet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kidneyweakx/fishnet/releases/download/v0.1.0/fishnet_0.1.0_darwin_arm64.tar.gz"
      sha256 "50748d4df6be804b8a09b2376c6f6d45145fac39f728806542828b7635bdbb6a"

      def install
        bin.install "fishnet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kidneyweakx/fishnet/releases/download/v0.1.0/fishnet_0.1.0_linux_x86_64.tar.gz"
      sha256 "fc6e9b2e8cd5282f4c9cec157eeb935d6a5fc7a3f3954bb1aa19718bbe1bf814"
      def install
        bin.install "fishnet"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kidneyweakx/fishnet/releases/download/v0.1.0/fishnet_0.1.0_linux_arm64.tar.gz"
      sha256 "4bfb0c4cabeec3f2f0f3184cd82cd0f3c89f9c7b492a85530e0e0038ed2b6b0d"
      def install
        bin.install "fishnet"
      end
    end
  end

  test do
    system "#{bin}/fishnet", "--help"
  end
end
